# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough","smart","tables","with_toc_data"]
highlighter:         pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            MinMini
tagline:          ""
description:      'Stock analysis & Investment notes'
url:              http://gitforwork.github.io/
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'MinMini'
  url:            http://gitforwork.github.io/

# Custom vars
version:          1.0
me:               Karthick AK

github:
  repo:           https://github.com/gitforwork/gitforwork.github.io


disqusShortName:
twitterAccountName:
facebookDevAppId:
googleAnalyticsSuperProxyQuery:
