# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["strikethrough","smart","with_toc_data"]
highlighter:         pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            Modhal Investments
tagline:          ""
description:      'Stock analysis and investment notes'
url:              http://gitlook.github.io/
baseurl:          '/'
paginate:         1
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'Karthick AK'
  url:            http://gitlook.github.io/

# Custom vars
version:          1.3.0

github:
  repo:           https://github.com/gitlook/gitlook.github.io


disqusShortName:
twitterAccountName:
facebookDevAppId:
googleAnalyticsSuperProxyQuery:
