# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /posts/:title/

# Setup
title:            GreenMirage
tagline:          ""
description:      'Personal blog'
url:              http://greenmirage.com/
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'GreenMirage'
  url:            http://greenmirage.com/

# Custom vars
version:          1.0
me:               pattam.onnu

github:
  repo:           https://github.com/gitforwork/gitforwork.github.io


disqusShortName:  greenmirage
twitterAccountName:
facebookDevAppId:
googleAnalyticsSuperProxyQuery:
