# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /posts/:title/

# Setup
title:            FrontSimple
tagline:          ""
description:      'For the informed immigrant. H1b, H4-EAD, EB-5 visas'
url:              https://frontsimple.com/
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'FrontSimple'
  url:            https://frontsimple.com/

# Custom vars
version:          1.0
me:               pattam.onnu

github:
  repo:           https://github.com/gitforwork/gitforwork.github.io


disqusShortName:  greenmirage
twitterAccountName:
facebookDevAppId:
googleAnalyticsSuperProxyQuery:
